sudo: false
language: node_js
node_js:
- stable
- 5
- 4
- iojs
- 0.12
- 0.11
- 0.1
before_install:
- npm install -g npm
env:
  global:
  - secure: he3kGOmSy6s97OdYRUq+k13w2WfIxzKfuDVysMfjOEV1U7YCq6tVeA6rm37yuyyaN3776he/fvPcK1Jd+FNfm8hzJMEu6QHqSd+Ri+q/32P+aXcEq2MEPMdsDAUpFqjT2p7BDPqH4a8DcJ0p48iXP+H2K3+HBaXNrneNLnU+6I8=
  - secure: OrRhONJzYW82KgMJbARL7Xyw1zuVc+2/t2l7Kv/gCzW0XeDyxK6caQh4RK1eprNw7dSmxSrTrzfmYKMvshu8PPJFKKDcXomYlkGLTUDezQkocm+turucDFvQPKtw23WG7rOeCLwbqXFJ0v3o8NwAsQuujpre/8k2o80icxSwrtg=
  - secure: PQvBYiC1DkO1yIjdSQemAjl8hjSunzI2M1tztzjmXy8Q7dAUVG7xpckXo+YEZte0scrPpImXPmBJYJFpHDI9fjD5PcYhy5j9B1EIHezujhdpzR2ZkNbUmBQFTOSvseJ/cbs/0nUrxsyEWjnUVqaete4n0mTu/hqk0G5sp9NA9nc=
script: make travis
