ui: tape
browserify:
  - transform: brfs
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: 25..latest
  - name: ie
    version: 9..latest
  - name: iphone
    version: latest
  - name: safari
    version: 6..latest
  - name: microsoftedge
    version: latest
  - name: android
    version: latest
