ui: tape
concurency: 2
browserify:
  - transform: brfs
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: ie
    version: latest
  - name: iphone
    version: latest
  - name: safari
    version: latest
  - name: microsoftedge
    version: latest
  - name: android
    version: latest
