ui: tape
concurrency: 1
browserify:
  - transform: brfs
browsers:
  - name: chrome
    version: latest
    platform: Mac 10.9
  # - name: firefox
  #   version: latest
  # - name: ie
  #   version: latest
  # - name: iphone
  #   version: latest
  # - name: safari
  #   version: latest
  # - name: microsoftedge
  #   version: latest
  # - name: android
  #   version: latest
